version: '3.8'

services:
  app:
    build: .
    container_name: backend_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/accommodations_app
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: accommodations_app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
  node_modules:
