version: '3.8'

services:
  app:
    build: .
    container_name: backend_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:password@mysql_db:3306/accommodations_app
      - JWT_SECRET=your_jwt_secret
    depends_on:
      mysql_db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: sh -c "npx prisma migrate deploy && node index.js"

  mysql_db:
    image: mysql:8
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: accommodations_app
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  dbdata:
  node_modules:
